# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches-ignore:
      - '!master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  autotests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install env
        run: npm i

      - name: Run API tests
        if: always()
        run: npm run test
        continue-on-error: true
        
      - name: Generate Allure Report
        if: always()
        run: allure generate --clean 
        continue-on-error: true
